# Define the number of ticks a hopper is on cooldown after pushing, pulling or picking up an item.
# Default: 8
hopper.transferCooldown: 8
# Define the number of items the hopper tries to push, pull or pick up when updated.
# Default: 1
hopper.itemsPerUpdate: 1
# Define how many hoppers are allowed to be updated every tick.
# Default: 0 (disabled)
hopper.updatesPerTick: 0